# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-25 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['c_time'], 'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
    ]
