# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('introduction', models.CharField(max_length=1024)),
                ('userName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_goods', to='login.User')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/%y/%m/%d')),
                ('goodsName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_picture', to='shopping.Goods')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'ordering': ['image'],
            },
        ),
    ]
