# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='goodsName',
        ),
        migrations.AddField(
            model_name='goods',
            name='imagePath',
            field=models.ImageField(default='', upload_to='upload/%y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
