# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20190221_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='kind',
            field=models.CharField(choices=[('MW', "Men's wear"), ('WW', "Women's wear"), ('CW', 'Children wear')], default="Men's wear", max_length=32),
        ),
    ]
