# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-21 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_goods_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='kind',
            field=models.CharField(choices=[('MW', "Men's wear"), ('WW', "Women's wear"), ('CW', "Children's wear")], default="Men's wear", max_length=32),
        ),
    ]
