# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-22 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20190222_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='imagePath',
            field=models.ImageField(blank=True, default='', null=True, upload_to='upload/%y/%m/%d'),
        ),
    ]
