# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-22 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20190222_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='userName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_goods', to='login.User'),
        ),
    ]
